baseURL = "https://atomscott.github.io/Sportech-Sanity/"
languageCode = "en-us"
title = "Sportech Sanity"
theme = "berbera"

timeout = 50000

pygmentsCodeFences=true
pygmentsUseClasses=true
canonifyURLs=true
publishDir="docs"
disableKinds = ["section", "taxonomyTerm"]

[taxonomies]
  author = "authors"
  tag = "tags"
  category = "categories"
